<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup>
    <!-- CI用: OpenSiv3D を展開したフォルダ -->
    <IncludePath Condition="Exists('$(SIV3D_0_6_16)\Siv3D\include\Siv3D.hpp')">
      $(SIV3D_0_6_16)\Siv3D\include;$(SIV3D_0_6_16)\Siv3D\include\ThirdParty;$(IncludePath)
    </IncludePath>
    <LibraryPath Condition="Exists('$(SIV3D_0_6_16)\Siv3D\lib\Windows\s3d.lib')">
      $(SIV3D_0_6_16)\Siv3D\lib\Windows;$(LibraryPath)
    </LibraryPath>
  </PropertyGroup>
</Project>
